# Generated by Django 5.2 on 2025-05-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
